# Generated by Django 6.0.2 on 2026-02-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='Untitled', max_length=50),
            preserve_default=False,
        ),
    ]
