# Generated by Django 6.0.2 on 2026-03-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0002_post_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
