# Generated by hand to add CategorySubscription model after existing migrations
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('NewsPortal', '0004_commentvote_postvote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='NewsPortal.categories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('category', 'user')},
            },
        ),
    ]
